# Generated by Django 6.1.1 on 2026-09-16 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(related_name='entrenadores', to='categorias.categoria')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'entrenador'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
            },
        ),
    ]
