# Generated by Django 6.1.1 on 2026-09-15 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('edad_minima', models.PositiveIntegerField(help_text='Edad mínima de los jugadores aceptados')),
                ('edad_maxima', models.PositiveIntegerField(help_text='Edad máxima de los jugadores aceptados')),
                ('telefono', models.CharField(max_length=20)),
                ('instagram', models.URLField(blank=True, help_text='Link al perfil de Instagram')),
                ('facebook', models.URLField(blank=True, help_text='Link a la página de Facebook')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escuelas/logos/')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='escuelas/instalaciones/')),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='escuelas.escuela')),
            ],
        ),
    ]
