# Generated by Django 6.1.1 on 2026-09-16 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(help_text='Ej: Enero 2026', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('abonado', 'Abonado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('registrado_por', models.CharField(blank=True, help_text='Quién recibió el pago', max_length=100)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
