# Generated by Django 6.1.1 on 2026-09-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadopago',
            options={},
        ),
        migrations.RemoveField(
            model_name='estadopago',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='estadopago',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='estadopago',
            name='valor_abonado',
        ),
        migrations.AlterField(
            model_name='estadopago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadopago',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_pago', to='jugadores.jugador'),
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('metodo', models.CharField(blank=True, max_length=50)),
                ('estado_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='pagos.estadopago')),
            ],
        ),
    ]
