# Generated by Django 6.1.1 on 2026-09-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrenamientos', '0001_initial'),
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='entrenamientos.entrenamiento')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='jugadores.jugador')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('entrenamiento', 'jugador')},
            },
        ),
    ]
