# Generated by Django 6.1.1 on 2026-09-16 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sub-10, Sub-12, Sub-15', max_length=50)),
                ('edad_minima', models.PositiveIntegerField()),
                ('edad_maxima', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='escuelas.escuela')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['edad_minima'],
            },
        ),
    ]
